/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGUI;

import excepciones.MyException;
import gestores.GestorDB;
import gestores.GestorFicheros;
import gestores.GestorMercancias;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Almacen;
import modelo.Mercancia;

/**
 *
 * @author Sergio
 */
public class VentanaMenu extends javax.swing.JFrame implements WindowListener {

    /**
     * Creates new form VentanaInicio
     */
    GestorDB con;

    /**
     * constructor de la ventana login
     */
    public VentanaMenu(GestorDB con) {
        initComponents();
        this.addWindowListener(this);
        this.con = con;
        this.setVisible(true);
        contenedor = (JPanel) this.getContentPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        labelAlmacen = new javax.swing.JLabel();
        botonEntradaMer = new javax.swing.JButton();
        botonSalidaMer = new javax.swing.JButton();
        botonList = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAlmacen.setText("ALMACÉN");

        botonEntradaMer.setText("Entrada de Mercancía");
        botonEntradaMer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntradaMerActionPerformed(evt);
            }
        });

        botonSalidaMer.setText("Salida de mercancía");
        botonSalidaMer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalidaMerActionPerformed(evt);
            }
        });

        botonList.setText("LISTADO");
        botonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSalir)
                            .addComponent(botonList)
                            .addComponent(labelAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSalidaMer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEntradaMer, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(botonEntradaMer)
                .addGap(35, 35, 35)
                .addComponent(botonSalidaMer)
                .addGap(32, 32, 32)
                .addComponent(botonList)
                .addGap(31, 31, 31)
                .addComponent(botonSalir)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed

        System.out.println(GestorMercancias.listadoSINSTOCK());
        fin();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonEntradaMerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntradaMerActionPerformed
        try {
            ArrayList<Almacen> alm = GestorFicheros.leoDatos();
            JOptionPane.showMessageDialog(this, "ficheros leidos correctamente");
            for (Almacen a : alm) {
                con.actualizarMercanciaDesdeFich(a);
                //aqui voy a comprobar las dos cosas, que esten en el array list y que esten sin existencias
                if (a.getCantidad() <= 0 && !GestorMercancias.compruebaListadoSIN(a)) {
                    //de momento lo dejo asi intentare cambiarlo a mercancia
                    GestorMercancias.altaSIN(a);
                } else if (GestorMercancias.compruebaListadoSIN(a) && a.getCantidad() > 0) {
                    GestorMercancias.bajaSIN(a);
                }
                if (!con.comprobarNuevo(a, con.ArrayMercancias())) {
                    GestorFicheros.guardoDatosNuevos(a);
                }

            }
        } catch (MyException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_botonEntradaMerActionPerformed

    private void botonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListActionPerformed
        VentanaListado vL = new VentanaListado(this);
        vL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonListActionPerformed

    private void botonSalidaMerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalidaMerActionPerformed
        VentanaSalida vS = new VentanaSalida(this, this.con);
        vS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonSalidaMerActionPerformed

    private void fin() {

        try {
            con.cerrarConexion();
        } catch (MyException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        System.exit(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEntradaMer;
    private javax.swing.JButton botonList;
    private javax.swing.JButton botonSalidaMer;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel labelAlmacen;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowClosing(WindowEvent e) {
        fin();
    }

    @Override
    public void windowClosed(WindowEvent e) {
        fin();
    }

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
